version: "3.8"

services:
  php-apache:
    build: .
    container_name: php_app
    ports:
      - "8080:80"  # Mapping port lokal ke container
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://postgres:12345@postgres:5432/postgres
    volumes:
      - ./src:/var/www/html

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
